config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "items#index"

  get 'users/mylisted'

  resources :items, shallow: true do
    resources :contact, only: [:show]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def show
    @item = Item.find(params[:id])
    @owner = User.find(@item.user_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all


    if params[:search].present? || params[:keywordsearch].present?


      if params[:search][:location].present?
        @location = true
        @items = @items.where(location: params[:search][:location])
      end

      if params[:search][:occasion].present?
        @occasion = true
        @items = @items.where(occasion: params[:search][:occasion])
      end

      if params[:keywordsearch].present?
        @items = @items.where('name LIKE ?', "%#{params[:keywordsearch]}%")
      end

    end

      if @items.empty?
        flash[:notice] = "Sorry, no items match your Search criteria."
      end


  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to '/'
    else
      flash[:notice] = "Your pin has not been submitted."
      redirect_to '/'
    end
  end

  def show
    @item = Item.find(params[:id])
    @owner = User.find(@item.user_id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to "/items/#{@item.id}"
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "Your pin has been removed successfully"
    redirect_to '/'
  end

end

def item_params
  params.require(:item).permit(:name, :description, :location, :PCNumber, :PCValue, :year, :price, :photo, :occasion)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def mylisted
    @my_items = Item.where(:user_id => current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/show.html.erb
<h1>Contact Form for: <%= @item.name %></h1>
<p><%= @owner.email %></p>

app/views/items/_form.html.erb
<%= form_for @item, html: {class: 'pure-form pure-form-aligned', multipart: true} do |f| %>
  <section class='pure-control-group'>
    <%= f.label :name %>
    <%= f.text_field :name, size: "60", placeholder: '50 character limit' %><br/>
  </section>
  <section class='pure-control-group'>
    <%= f.label :description %>
    <%= f.text_area :description, size: "", placeholder: '250 character limit', class: 'pure-input-2-3'%><br/>
  </section>
  <section class='pure-control-group'>
    <%= f.label :location %>
    <%= f.collection_select :location, Item::LOCATIONS, :to_s, :titleize %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :occasion %>
    <%= f.collection_select :occasion, Item::OCCASIONS, :to_s, :titleize, prompt: 'n/a' %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :price %>
    <%= f.text_field :price, size: "60", placeholder: 'Number only (US$)' %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :Pin_Catalog_Number %>
    <%= f.text_field :PCNumber, size: "60", placeholder: 'HRC Pin Catalog Number (if known)' %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :Pin_Catalog_Value %>
    <%= f.text_field :PCValue, size: "60", placeholder: 'HRC Pin Catalog Value (if known)' %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :year %>
    <%= f.text_field :year, size: "60", placeholder: 'Year of Issue (if known)' %>
  </section>
  <section class='pure-control-group'>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </section>
  <section class="pure-controls">
    <%= f.submit 'Submit Item', class: 'pure-button pure-button-primary' %>
  </section>
<% end %>

app/views/items/edit.html.erb
<% if current_user %>
  <% if current_user.id == @item.user_id %>
    <p>Edit <%= @item.name %></p>
    <%= render "form" %>
  <% else %>
    <p>You are not allowed to edit this item</p>
  <% end %>
<% else %>
  <p>You must be logged in (and the owner) to edit this page.</p>
<% end %>

app/views/items/index.html.erb
<section "indexwrap">
  <section class="leftcol">
    <h3>Search Pins</h3>
    <%= form_tag items_path, :method => 'get', html: {class: 'pure-form pure-form-aligned', multipart: true} do %>
      <section class='pure-control-group'>
        <%= label_tag :location %>
        <%= collection_select(:search, :location, Item::LOCATIONS, :to_s, :titleize, prompt: (@location ? params[:search][:location] : 'n/a')) %>
      </section>
      <br/>
      <section class='pure-control-group'>
        <%= label_tag :occasion %>
        <%= collection_select(:search, :occasion, Item::OCCASIONS, :to_s, :titleize, prompt: (@occasion ? params[:search][:occasion] : 'n/a')) %>
      </section>
      <br/>
      <section class='pure-control-group'>
        <%= label_tag :keyword %>
        <%= text_field_tag :keywordsearch, params[:keywordsearch] %>
      </section>
      <br/>
      <section class='pure-controls'>
        <%= submit_tag "Search", :name => nil %>
      </section>
    <% end %>

    <% if current_user %>
      <section class="userarea">
        <h3>Admin</h3>
        <% if current_user %>
          <p><%= link_to 'Add a new Pin', new_item_path, class:"addnew" %></p>
          <p><%= link_to 'Manage My Listed Pins', users_mylisted_path, class:"addnew" %></p>
        <% end %>
      </section>
    <% end %>

  </section>



  <section class="midcol">
    <% if @items.any? %>
      <% @items.each do |item| %>
        <%= link_to item do %>
          <section class="item_image">
            <p class="item_name">
              <%= item.name %> (<%= item.location.humanize.titleize %>)
            </p>
            <p class="image_thumb">
              <%= image_tag item.photo.url(:thumb) %>
            </p>
          </section>
        <% end %>
      <% end %>

    <% else %>
      <p class="no_match">Sorry, no items match your Search criteria.</p>
    <% end %>

  </section>



</section>

app/views/items/new.html.erb
<% if current_user %>
  <br/>
  <%= render "form" %>
<% else %>
  <p>You must be registered to list a new pin</p>
<% end %>

app/views/items/show.html.erb
<section class='indexwrap'>

  <section class='leftcol'>
    <section class='contact_link_holder'>
      <section class='contact_button'>
        <%= link_to contact_path, :target => "_blank", class:'contact_link' do %>
          <h3 class='contact_text'>Contact Seller</h3>
        <% end %>
      </section>
    </section>
    <section class='key_info'>
      <p><strong>Price:</strong> $<%= @item.price %></p>
      <p><strong>Location:</strong> <%= @item.location %></p>
      <p><strong>Occasion:</strong> <%= @item.occasion %></p>
      <p><strong>Year:</strong> <%= @item.year %></p>
      <% if @item.PCNumber %>
        <p><strong>Pin Catalog Number:</strong> <%= @item.PCNumber %></p>
      <% end %>
      <% if @item.PCValue %>
        <p><strong>Pin Catalog Value:</strong> $<%= @item.PCValue %></p>
      <% end %>
    </section>
    <% if current_user %>
      <% if current_user.id == @item.user_id %>
        <section class='userarea'>
          <%= link_to 'Edit', edit_item_path %>
          <%= link_to "Delete", item_path, method: :delete %>
        </section>
      <% end %>
    <% end %>
  </section>

  <section class='midcol'>
    <section class='item_name_show'>
      <h1><%= @item.name %></h1>
    </section>

    <section class='image_medium_holder'>
      <%= image_tag @item.photo.url(:medium), class:'image_medium' %>
    </section>
    <section>

      <p class='description'><strong>Description:</strong> <%= @item.description %></p>

    </section>

  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRC Pins For Sale</title>
  <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <section id="logo">
      <%= link_to image_tag("logo_100x70wh.png"), root_path %>
    </section>
    <nav>
      <% if current_user %>
        <section class="signedin">
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "sign" %>
        </section>
          <p class="welcome">Welcome, <%= current_user.email %></p>
      <% else %>
        <section class="signinup">
          <%= link_to "Sign Up", new_user_registration_path, class: "sign" %>
          <%= link_to "Sign In", new_user_session_path, class: "sign" %>
        </section>
        <p class="membership">Currently, you only need membership to sell your pins, not to purchase them.</p>
      <% end %>
    </nav>
  </header>
  <section class="main">
    <section class="notices">
      <%= notice %>
      <%= alert %>
    </section>

    <%= yield %>

  </section>
</body>
</html>

app/views/users/mylisted.html.erb
<ul>
  <% @my_items.each do |item| %>
    <li><%= item.name %>
      <ul>
        <li><%= link_to 'Edit', edit_item_path(item) %> <%= link_to "Delete", item_path(item), method: :delete, data: {confirm: "Are you sure?"} %></li>
      </ul>
    </li>
  <% end %>
</ul>